### ISSUE TITLE
Forecast function is not executable

### ISSUE THREAD

**Issue by OlegIvanytskyi** [romainlafarguette/varfxi#1]
Hello! When trying to reproduce the code in the notebook, I encountered several issues. The main one is with the `forecast` function.

In the cell with the title **Baseline GARCH Model: Fit and Forecast**, there is a line `dgfor = dgf.forecast('2020-01-01', horizon=1)`. If you try to run it, the following error turns up:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-12-22a2564d592f> in <module>
     16 
     17 # Forecast 2020
---> 18 dgfor = dgf.forecast('2020-01-01', horizon=1)
     19 

~\Desktop\education\test\varfxi\modules\distGARCH.py in forecast(self, start_date, horizon, fmethod, sample_size)
    328     def forecast(self, start_date, horizon=1, fmethod='analytic',
    329                  sample_size=10000):
--> 330         return(DistGARCHForecast(self, start_date, horizon, fmethod,
    331                                  sample_size))
    332 

~\Desktop\education\test\varfxi\modules\distGARCH.py in __init__(self, DistGARCHFit, start_date, horizon, fmethod, sample_size)
    672 
    673         # Run the forecasts from the arch package
--> 674         self.forecasts = self.res.forecast(horizon=self.horizon, 
    675                                            start=self.start_date,
    676                                            method=self.fmethod)

c:\users\oleg\appdata\local\programs\python\python38\lib\site-packages\arch\univariate\base.py in forecast(self, params, horizon, start, align, method, simulations, rng, random_state, reindex, x)
   1504         if not isinstance(horizon, (int, np.integer)) or horizon < 1:
   1505             raise ValueError("horizon must be an integer >= 1.")
-> 1506         return self.model.forecast(
   1507             params,
   1508             horizon,

c:\users\oleg\appdata\local\programs\python\python38\lib\site-packages\arch\univariate\mean.py in forecast(self, params, horizon, start, align, method, simulations, rng, random_state, reindex, x)
    946         constant = arp[0] if self.constant else 0.0
    947         dynp = arp[int(self.constant) :]
--> 948         expected_x = self._reformat_forecast_x(x, horizon, start_index)
    949         mean_fcast = _ar_forecast(
    950             self._y, horizon, start_index, constant, dynp, expected_x, exog_p

c:\users\oleg\appdata\local\programs\python\python38\lib\site-packages\arch\univariate\mean.py in _reformat_forecast_x(self, x, horizon, start)
    799                 return np.empty(0)
    800             else:
--> 801                 raise TypeError(
    802                     "x is None but the model contains exogenous variables. You must "
    803                     "provide expected values to use for the exogenous variables to "

TypeError: x is None but the model contains exogenous variables. You must provide expected values to use for the exogenous variables to construct forecasts.
```

It looks like there is a problem with parameters, but I can't figure out how to solve it. As a consequence, many cells after this one cannot be run.

Would appreciate any help!

**Comment by romainlafarguette** [comment]
The error message is quite clear: "You must provide expected values to use for the exogenous variables to construct forecasts."

Basically, if you fit a model y(t+1) = alpha + beta*y(t) + gamma*x(t+1), you need to have a the values for x(t+1) for the projections. 

Try first without exogeneous variables to see if the model works

**Comment by OlegIvanytskyi** [comment]
But how do I provide these values if the function `forecast` does not accept such parameters? I was just running the cells in the original notebook, expecting it to work. Where and what do I have to change to get the same output?

**Comment by romainlafarguette** [comment]
Sorry for the late reply, I was on leave. You say that you are executing the exact original output? This is weird, because I have asked two colleagues to try it and they don't have issue. I assume that you have an issue with cell 6, the one where the first forecast is done:

# Fit the model
dgf = dg.fit()

# Forecast 2020
dgfor = dgf.forecast('2020-01-01', horizon=1)


Could you confirm to me that the fit runs well? (dggf = dg.fit())

**Comment by OlegIvanytskyi** [comment]
That is correct. If I comment the line `dgfor = dgf.forecast('2020-01-01', horizon=1)`, everything runs fine, even some of the next cells. But the function `forecast` gives me an error: `TypeError: x is None but the model contains exogenous variables. You must provide expected values to use for the exogenous variables to construct forecasts`

**Comment by romainlafarguette** [comment]
Dear Oleg. I am so sorry for this issue. My company just updated our Python distribution and I now can replicate the problem you encountered !! The reason is because the ARCH package forecast function has been revamped after 4.19 (please refer to the warnings in  : https://arch.readthedocs.io/en/latest/univariate/univariate_volatility_forecasting.html ). I wasn't able to see it earlier as our Python and ARCH versions were pretty old... I am sorry for that. 

I have corrected the codes, hopefully they should work now (at least on my computer !). Please note however that the random seed generator has also changed in the new version, and I can't reproduce exactly the same results as in the IMF WP 2020, but the results are very close (just a small difference with the error sampler). So don't be surprised if you see small differences. I have updated the README accordingly. 

Thanks a lot and sorry for having been so long to fix the issue, I wasn't able to do it with my outdated Python distribution...

**Comment by OlegIvanytskyi** [comment]
It works! With `arch==4.19` everything goes great. It still gives me an error when using the latest `arch` version, but I can execute all the code with version `4.19`. Thank you so much and no worries!

**Comment by romainlafarguette** [comment]
Excellent, I am glad this works ! I will update it in the future with the new version of ARCH, once the new version are installed by the IMF on my computer. I have to be consistent with the distribution used at the Fund unfortunately, as my codes are used by colleagues on mission. This is why there is a gap between my github and the latest version of ARCH. The IMF updates the Python version infrequently, and often not with the latest packages... Let us keep in touch in the future, in case there are other problems. 

Best, 

Romain
